name: conduit_open_api
version: 4.4.1
homepage: https://gitlab.com/revenants/openapi-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications. Supports OpenApi v3.1
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  conduit_codable: ^4.4.0
  meta: ^1.1.5
dev_dependencies:
  lints: ^2.0.1
  test: ^1.3.0
